'use strict';

const en = {
  REPORT_VARIABLES_UNSUPPORTED: 'This report uses variable filters. Configure a supported report model before binding it to Canvas.',
  REPORT_EMPTY_RESULT_MISMATCH: 'The report has matching results but returned no rows for this page.',
  REPORT_JSON_INVALID: 'The report returned non-JSON content. Check the session and retry.',
  REPORT_INVALID_RESPONSE: 'The report returned an invalid response.',
  REPORT_QUERY_FAILED: 'The report query failed.',
  REPORT_TRACE_ID_MISSING: 'The asynchronous report query returned no trace ID.',
  REPORT_ROWS_MISSING: 'The report response contains no recognizable row data.',
  REPORT_META_INVALID: 'The report column metadata does not match its rows.',
  REPORT_ROW_INVALID: 'The report returned an invalid row.',
  REPORT_TOTAL_INVALID: 'The report returned an invalid total count.',
  REPORT_SCHEMA_INVALID: 'The report Schema could not be read.',
  REPORT_NAVIGATION_NOT_UNIQUE: 'The report is missing or ambiguous in this application navigation. Check access and binding.',
  REPORT_APP_MISMATCH: 'The report and Canvas must belong to the same application.',
  REPORT_TOPIC_MISSING: 'The report navigation contains no topic ID.',
  REPORT_BINDING_INCOMPLETE: 'The report binding is incomplete. Read the current report Schema.',
  REPORT_FILTER_INVALID: 'Report filters require configured keys and arrays of values.',
  REPORT_PAGING_INVALID: 'Report paging requires a nonnegative offset and a page size from 1 to 100.',
  REPORT_ORDER_INVALID: 'The report sort field or direction is invalid.',
  REPORT_ABORTED: 'The report query was cancelled.',
  REPORT_TIMING_INVALID: 'Report timeout and polling interval must be positive.',
  REPORT_TIMEOUT: 'The report query timed out. Narrow the filters and retry.',
  REPORT_APP_CONTEXT_MISSING: 'The current application could not be resolved from the page URL.',
  REPORT_CSRF_MISSING: 'The page has no CSRF token. Refresh the page and sign in again.',
  REPORT_HTTP_401: 'The session expired. Sign in again.',
  REPORT_HTTP_403: 'Access to this report was denied. Check report permissions and the session.',
  REPORT_LOGIN_REDIRECT: 'The request was redirected. Refresh the page and sign in again.',
  REPORT_SCHEMA_ID_MISMATCH: 'The returned Schema belongs to a different report.',
  REPORT_BINDING_NOT_FOUND: 'The configured component or dataset no longer exists in this report.',
  REPORT_DISPOSED: 'The report bridge has been disposed.',
};
const zh = {
  REPORT_VARIABLES_UNSUPPORTED: '该报表使用变量筛选，当前 Canvas 集成尚未支持，请先配置受支持的报表模型。',
  REPORT_EMPTY_RESULT_MISMATCH: '报表总数大于零，但当前有效页没有返回行数据，请检查查询和绑定。',
  REPORT_JSON_INVALID: '报表返回内容不是 JSON，请检查登录状态后重试。',
  REPORT_INVALID_RESPONSE: '报表接口返回结构异常。',
  REPORT_QUERY_FAILED: '报表查询失败。',
  REPORT_TRACE_ID_MISSING: '异步报表查询未返回 traceId，无法继续获取结果。',
  REPORT_ROWS_MISSING: '报表返回体未包含可识别的行数据，请检查数据绑定。',
  REPORT_META_INVALID: '报表列元数据与行数据不匹配。',
  REPORT_ROW_INVALID: '报表返回了无法识别的行数据。',
  REPORT_TOTAL_INVALID: '报表返回的总数格式异常。',
  REPORT_SCHEMA_INVALID: '无法解析报表 Schema。',
  REPORT_NAVIGATION_NOT_UNIQUE: '当前应用导航中未找到唯一报表，请检查访问权限和绑定。',
  REPORT_APP_MISMATCH: '报表与 Canvas 必须属于同一应用。',
  REPORT_TOPIC_MISSING: '报表导航未返回 topicId。',
  REPORT_BINDING_INCOMPLETE: '报表绑定不完整，请读取当前报表 Schema。',
  REPORT_FILTER_INVALID: '筛选键必须来自该报表数据集，筛选值必须为数组。',
  REPORT_PAGING_INVALID: '报表起始位置必须为非负整数，每页数量须为 1 至 100。',
  REPORT_ORDER_INVALID: '报表排序字段或排序方向无效。',
  REPORT_ABORTED: '报表查询已取消。',
  REPORT_TIMING_INVALID: '报表超时和轮询间隔必须大于零。',
  REPORT_TIMEOUT: '报表查询超时，请缩小筛选范围后重试。',
  REPORT_APP_CONTEXT_MISSING: '无法从页面地址确定当前应用。',
  REPORT_CSRF_MISSING: '页面缺少 CSRF 信息，请刷新页面并重新登录。',
  REPORT_HTTP_401: '登录已失效，请重新登录。',
  REPORT_HTTP_403: '无权访问报表，请检查报表权限和登录状态。',
  REPORT_LOGIN_REDIRECT: '查询发生重定向，请刷新页面并重新登录。',
  REPORT_SCHEMA_ID_MISMATCH: '返回的 Schema 与绑定报表不一致。',
  REPORT_BINDING_NOT_FOUND: '报表中未找到绑定的组件或数据集，请重新检查绑定。',
  REPORT_DISPOSED: '报表数据桥已销毁。',
};
module.exports = { en, zh };
